image: Visual Studio 2015

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015 Win64"
      CONFIG: Release
      PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"

platform:
  - x64

matrix:
  fast_finish: true

install:
  - md C:\dev
  - ps: Invoke-WebRequest https://github.com/osrf/opensplice/releases/download/6.4.0-0/opensplice-Win64VS2013-with-VS2015-patch.zip -OutFile C:\dev\opensplice.zip
  - 7z x -bso0 C:\dev\opensplice.zip -oC:\dev
  - ps: Invoke-WebRequest https://github.com/ros2/ros2/releases/download/release-alpha8/ros2-alpha8-package-windows-opensplice.zip -OutFile C:\dev\ros2.zip
  - 7z x -bso0 C:\dev\ros2.zip -oC:\dev
  - ren C:\dev\ros2-windows ros2
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\vsvars32.bat"
  - ps: |
      gci -r -path "C:\dev\ros2" -include "*.bat","*.py" |
      foreach-object { $a = $_.fullname; ( get-content $a ) |
      foreach-object { $_ -replace "C:\\ProgramData\\chocolatey\\lib\\python3\\tools\\python.exe","C:\\Python35-x64\\python.exe" }  |
      set-content $a }
  - call C:\dev\ros2\setup.bat

before_build:
  - md temp
  - md temp\ament_boost_process
  - for /f "delims=" %%a IN ('dir "." /b') do if NOT "temp" == "%%a" move "%%a" temp\ament_boost_process\
  - ren temp src
  - ps: Invoke-WebRequest https://github.com/geoffviola/ament_boost/releases/download/0.0.0/ament_boost_x64_windows.zip -OutFile ament_boost.zip
  - 7z x -bso0 ament_boost.zip
  - ren ament_boost_x64_windows install
  - call install\local_setup.bat

build_script:
  - ament build

after_build:
  - xcopy /e /c /i /y install ament_boost_process_windows
  - 7z a -bso0 -tzip ament_boost_process_windows.zip ament_boost_process_windows

test: ament test

artifacts:
  - path: ament_boost_process_windows.zip
    name: ament_boost_process_windows

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: uPmcYA+EiDxIJIyXU9HsXMOn00rRjdWjYaYB7kd77BZSWQOgitaJONWInELIDxdw
  artifact: ament_boost_process_windows.zip
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true